# Generated by Django 3.0.3 on 2021-03-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='summary',
            name='summary',
            field=models.CharField(default='test', max_length=1500),
        ),
    ]
