# Generated by Django 3.0.3 on 2021-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_summary', '0003_auto_20210315_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
