# Generated by Django 3.0.3 on 2020-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0003_sentiments_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments_form',
            name='text',
            field=models.TextField(),
        ),
    ]
