# Generated by Django 3.0.3 on 2020-08-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0004_auto_20200830_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments_form',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
