# Generated by Django 3.0.3 on 2020-08-30 22:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_classification', '0005_auto_20200830_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sentiments_form',
            new_name='Sentiments',
        ),
    ]
