# Generated by Django 3.0.3 on 2020-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0006_auto_20200830_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
