# Generated by Django 3.0.3 on 2021-02-25 00:24

from django.db import migrations, models
import document_sentiment.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment_documents',
            name='document',
            field=models.FileField(upload_to=document_sentiment.models.upload_to),
        ),
    ]
