# Generated by Django 3.0.3 on 2021-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_sentiment', '0002_auto_20210225_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
